# WEATHER TASK

In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\simon\Desktop\Data Analysis Projects\Python tasks - Weather; Udemy; London Housing\Datasets\Weather data.csv")
df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [137]:
df.shape

(8784, 8)

In [139]:
df.index

RangeIndex(start=0, stop=8784, step=1)

In [141]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [143]:
df.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [145]:
#1. FIND ALL THE UNIQUE 'wind speed' VALUES

df['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [147]:
#2. FIND THE NUMBER OF TIMES WHEN THE 'weather is exactly Clear'

df.Weather

0                        Fog
1                        Fog
2       Freezing Drizzle,Fog
3       Freezing Drizzle,Fog
4                        Fog
                ...
8779                    Snow
8780                    Snow
8781                    Snow
8782                    Snow
8783                    Snow
Name: Weather, Length: 8784, dtype: object

In [149]:
df ['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [151]:
df.head(20)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,1/1/2012 7:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,1/1/2012 8:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,1/1/2012 9:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,1/1/2012 10:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,1/1/2012 11:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,1/1/2012 12:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,1/1/2012 13:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,1/1/2012 14:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,1/1/2012 15:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,1/1/2012 16:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,1/1/2012 17:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,1/1/2012 18:00,3.8,1.0,82,15,12.9,99.74,Rain
19,1/1/2012 19:00,3.1,1.3,88,15,12.9,99.68,Rain

In [153]:
df['Weather']=='Clear'

0       False
1       False
2       False
3       False
4       False
        ...
8779    False
8780    False
8781    False
8782    False
8783    False
Name: Weather, Length: 8784, dtype: bool

In [155]:
df[df['Weather']=='Clear'].shape

(1326, 8)

In [157]:
no_of_clear = df[df['Weather']=='Clear'].shape[0]
no_of_clear

1326

In [159]:
df['Weather']!='Clear'

0       True
1       True
2       True
3       True
4       True
        ...
8779    True
8780    True
8781    True
8782    True
8783    True
Name: Weather, Length: 8784, dtype: bool

In [161]:
#3. FIND THE NUMBER OF TUMES WHEN THE the 'Wind Speed was exactly 4km/h'

df['Wind Speed_km/h']==4

0        True
1        True
2       False
3       False
4       False
        ...
8779    False
8780    False
8781    False
8782    False
8783    False
Name: Wind Speed_km/h, Length: 8784, dtype: bool

In [163]:
df[df['Wind Speed_km/h']==4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow

In [165]:
# Alternatively:
df[df['Wind Speed_km/h']==4]['Wind Speed_km/h'].count()

474

In [306]:
#4. RENAME 'Weather' column to 'Weather Condition'

df.rename(columns = {'Weather': 'Weather Condition'}, inplace = True)

#4.5. RENAME 'Press_kPa' to 'Pressure_kPa'
df.rename(columns = {'Press_kPa': 'Pressure_kPa'}, inplace = True)

df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Pressure_kPa,Weather Condition,Wind Speed
0,1/1/2012 0:00,-1.8,-3.9,86,24,8.0,101.24,Fog,24
1,1/1/2012 1:00,-1.8,-3.7,87,24,8.0,101.24,Fog,24
2,1/1/2012 2:00,-1.8,-3.4,89,24,4.0,101.26,"Freezing Drizzle,Fog",24
3,1/1/2012 3:00,-1.5,-3.2,88,24,4.0,101.27,"Freezing Drizzle,Fog",24
4,1/1/2012 4:00,-1.5,-3.3,88,24,4.8,101.23,Fog,24
...,...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,24,9.7,100.13,Snow,24
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow,24
8781,12/31/2012 21:00,-0.5,-1.5,93,24,4.8,99.95,Snow,24
8782,12/31/2012 22:00,-0.2,-1.8,89,24,9.7,99.91,Snow,24
8783,12/31/2012 23:00,0.0,-2.1,86,24,11.3,99.89,Snow,24